# 🐼 Pandas
### Learning Data Analysis Step by Step

---

> **What you will learn:** How to load, explore, and clean real data using Pandas  
> **Dataset:** Student Lifestyle & Exam Performance (1,150 students)  
> **Tip:** Run each cell one at a time. Read the explanation, then look at the output. 

---

## 📜 What is Pandas — and Where Did It Come From?

In **2008**, a programmer named **Wes McKinney** was working at a finance company in New York. Every day he had to analyse huge tables of data — stock prices, economic numbers, reports.

The tools available at the time were painful to use for this kind of work. So Wes built his own — and called it **pandas**.

The name comes from **"panel data"**, an economics term for data tracked over time. It also stands for **"Python Data Analysis"**.

He released it for free in **2009**. Today it is downloaded **100 million times every month** and used by Google, Netflix, NASA, and almost every data team in the world.

---

# 📊 Introduction to Pandas

## 📌 What is Pandas?
Pandas is a powerful Python library used for **data analysis and data manipulation**.  
It provides easy-to-use data structures for handling structured data like tables.

---

## 📌 Key Data Structures

- **Series** → 1D labeled array (like a column)  
- **DataFrame** → 2D table (rows and columns, like Excel sheet)

---

## 📌 Key Features of Pandas

- **Easy data handling** → Load, clean, and process data efficiently  
- **Data alignment** → Automatically aligns data by labels  
- **Handling missing data** → Provides functions to detect and fill missing values  
- **Filtering & selection** → Easily select specific rows and columns  
- **Grouping & aggregation** → Perform operations like sum, mean, count  
- **Merging & joining** → Combine multiple datasets  
- **Time series support** → Work with date and time data  
- **File handling** → Read/write data from CSV, Excel, JSON, HTML, SQL etc.

---

## 📌 Why Use Pandas?

- Simplifies complex data operations  
- Saves time compared to manual coding  
- Widely used in Data Science and AI  

---

## 📌 Applications in AI

- Data preprocessing  
- Cleaning datasets  
- Feature selection  
- Preparing data for machine learning models  

---

## 🤔 Why Do We Need Pandas?

Imagine you have a spreadsheet with 1,000 student records. You want to:
- Find all students who scored above 80
- Calculate the average score by gender
- Fix typos in the data

In plain Python you would write 30+ lines of code and loops.

With Pandas, each of those tasks is **one line**.

---

## 🏗️ The Two Main Building Blocks

**Series** → a single column of data (like one column in Excel)
```
0    85
1    72
2    91
3    68
```

**DataFrame** → a full table with rows and columns (like an entire Excel sheet)
```
   name   age  score
0  Alice   21     85
1  Bob     19     72
2  Carol   22     91
```

Everything we do in Pandas works with these two objects.

---
# Part 1 — Getting Started
---

### Step 1 — Import Pandas

Before using Pandas we need to import it. We give it the short nickname `pd` — this is the standard convention used by everyone in the world.

In [2]:
import pandas as pd

### Step 2 — Check the Version

Let's confirm Pandas is installed and see which version we have.

In [3]:
pd.__version__

'3.0.1'

### Step 3 — Create Your First Series

A **Series** is like a single list of values with labels (index) on the side. Think of it as one column of a spreadsheet.

In [4]:
# A simple series of exam scores
scores = pd.Series([85, 72, 91, 68, 95])
scores
#scores[2]

0    85
1    72
2    91
3    68
4    95
dtype: int64

### Step 4 — Series with Custom Labels

Instead of numbers (0, 1, 2...) we can use names as the index.

In [5]:
# Give each score a student name as the label
scores = pd.Series(
    [85, 72, 91, 68, 95],
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal']
)
scores

Ali      85
Sara     72
John     91
Sana     68
Bilal    95
dtype: int64

### Step 5 — Access One Value from a Series

Use the label (or position number) to get a single value.

In [6]:
# Get Ali's score by name
scores['Ali']

np.int64(85)

### Step 6 — Basic Math on a Series

Pandas does math on all values at once — no need to write a loop.

In [7]:
# Average score
scores.mean()

np.float64(82.2)

In [8]:
# Highest score
scores.max()

np.int64(95)

In [9]:
# Who scored above 80?
scores[scores > 80]

Ali      85
John     91
Bilal    95
dtype: int64

### Step 7 — Create Your First DataFrame

A **DataFrame** is a full table — like an Excel spreadsheet. We build it from a dictionary where each key is a column name and each value is a list of data.

In [10]:
# Create a small student table
data = {
    'name'        : ['Ali', 'Sara', 'John', 'Sana', 'Bilal'],
    'age'         : [21, 19, 22, 20, 21],
    'study_hours' : [5.5, 3.0, 7.2, 2.1, 6.8],
    'exam_score'  : [85, 72, 91, 68, 95]
}

students = pd.DataFrame(data)
students

    name  age  study_hours  exam_score
0    Ali   21          5.5          85
1   Sara   19          3.0          72
2   John   22          7.2          91
3   Sana   20          2.1          68
4  Bilal   21          6.8          95

### Step 8 — Get One Column from a DataFrame

Use square brackets with the column name, just like looking up a key in a dictionary.

In [11]:
# Get the exam_score column
students['exam_score']

0    85
1    72
2    91
3    68
4    95
Name: exam_score, dtype: int64

### Step 9 — Get Multiple Columns

Pass a **list** of column names inside the brackets.

In [12]:
# Get name and exam_score columns only
students[['name', 'exam_score']]

    name  exam_score
0    Ali          85
1   Sara          72
2   John          91
3   Sana          68
4  Bilal          95

---
# Part 2 — Loading Real Data
---

Now we move to our **real dataset** — 1,150 student records with messy, real-world data quality issues. This is what data actually looks like in the real world.

**Dataset columns:**
- Student ID, Age, Gender
- Study hours, Social media hours, Netflix hours
- Sleep hours, Attendance, Exercise frequency
- Diet quality, Internet quality, Mental health rating
- Part-time job, Parental education, Extracurricular activities
- **Exam Score** (what we want to understand!)

### Step 10 — Load the CSV File

`pd.read_csv()` reads a CSV file and turns it into a DataFrame automatically.

In [13]:
# df1 = pd.read_csv('student_habits_performance.csv')
# df1.describe()

In [14]:
# Load the dataset
# Make sure Messy_student_data.csv is in the same folder as this noteb
df_raw = pd.read_csv('Messy_student_data.csv')

### Step 11 — Make a Copy to Work On

Always keep the original raw data untouched. Work on a copy so you can always go back if something goes wrong.

In [15]:
# Work on this copy — never touch df_raw
df= df_raw.copy()
df = df_raw.copy()
# df.to_csv()

---
# Part 3 — Exploring the Data

Before cleaning or analysing anything, we need to **look at and understand** the data. This is always the first step.

---

### Step 12 — See the First 5 Rows

`head()` shows the first few rows. It is the quickest way to see what your data looks like.

In [16]:
df.head(10)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
5,S1005,23.193687,male,7.2,0.762742,4.156124,No,82.212347,NaN,Fair,-1.725755,Master,Average,4.610438,No,106.436337,1863
6,S1006,22.062970,femle,5.6,-0.033797,-3.916967,Yes,NaN,-4.759269743,Good,-3.266879,Master,Poor,2.176012,No,93.537529,4953
7,S1007,NaN,NaN,4.3,-0.912870,3.373847,Yes,76.041926,3.109453671639383,Fair,NaN,Bachelor,Average,4.307425,No,365.927950,2313
8,S1008,NaN,female,NaN,3.663144,6.903434,No,99.326218,4.4,Good,4.314662,NaN,Good,NaN,No,80.297148,5120
9,S1009,23.669075,FEMALE,4.8,5.199887,-0.088103,No,96.742474,7.054294851537139,Good,2.072327,Bachelor,NaN,11.481817,Yes,100.123883,2126

### Step 13 — See the Last 5 Rows

`tail()` shows the last few rows. Useful to check that the data ends properly.

In [17]:
df.tail()

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

### Step 14 — See a Random Sample

`sample()` picks random rows. Great for getting a feel for the data without always seeing the same rows.

In [18]:
df.sample(5)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
815,S1815,21.164812,NaN,2.9,-0.478137,-1.085227,No,73.288664,6.509409734562063,Poor,NaN,Master,Good,-2.356258,No,40.422871,3827
40,S1040,NaN,female,NaN,10.630424,-2.899003,No,97.026873,9.391981623707386,unknown,10.632410,Bachelor,Good,-1.787084,No,NaN,8930
1000,S1997,22.375577,M,3,6.194325,NaN,No,63.107560,6.692017287569668,Good,3.273857,Bachelor,Good,10.227351,Yes,63.545740,7295
825,S1825,NaN,mle,4.3,-0.240591,-1.344027,Yes,92.455027,4.246910990638644,Good,-2.789728,NaN,Average,7.596946,NaN,NaN,8654
481,S1481,21.474912,femle,ten,-0.008814,-2.066733,No,63.407893,13.31158375225136,Good,-1.519650,Master,Poor,7.343102,No,85.096744,7672

### Step 15 — Check the Size of the Data

`shape` tells us how many **rows** and **columns** we have. It returns `(rows, columns)`.

In [19]:
df.shape

(1153, 17)

### Step 16 — See All Column Names

`columns` lists every column name. Notice that some have **trailing spaces** — this will cause bugs later!

In [20]:
df.columns

Index(['student_id ', 'age ', 'GENDER', 'STUDY_HOURS_PER_DAY',
       'SOCIAL_MEDIA_HOURS', 'netflix_hours ', 'PART_TIME_JOB',
       'attendance_percentage ', 'SLEEP_HOURS', 'diet_quality ',
       'EXERCISE_FREQUENCY', 'PARENTAL_EDUCATION_LEVEL', 'INTERNET_QUALITY',
       'mental_health_rating ', 'EXTRACURRICULAR_PARTICIPATION', 'EXAM_SCORE',
       'RANDOM_ID'],
      dtype='str')

### Step 17 — Get a Full Overview with info()

`info()` is one of the most useful commands. It shows:
- Column names
- How many non-null (non-missing) values each column has
- The data type of each column

Look for columns where **non-null count is less than 1150** — those have missing values.

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1153 entries, 0 to 1152
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1032 non-null   str
 1   age                            1041 non-null   float64
 2   GENDER                         1039 non-null   str
 3   STUDY_HOURS_PER_DAY            998 non-null    str
 4   SOCIAL_MEDIA_HOURS             1044 non-null   float64
 5   netflix_hours                  1032 non-null   float64
 6   PART_TIME_JOB                  1032 non-null   str
 7   attendance_percentage          1039 non-null   float64
 8   SLEEP_HOURS                    1044 non-null   str
 9   diet_quality                   1047 non-null   str
 10  EXERCISE_FREQUENCY             1042 non-null   float64
 11  PARENTAL_EDUCATION_LEVEL       947 non-null    str
 12  INTERNET_QUALITY               1043 non-null   str
 13  mental_health_rating           1041 non-null   float64
 14  EXTRACURRICULAR_PARTICIPATION  1039 non-null   str
 15  EXAM_SCORE                     1039 non-null   float64
 16  RANDOM_ID                      1153 non-null   int64
dtypes: float64(7), int64(1), str(9)
memory usage: 153.3 KB

### Step 18 — Get Basic Statistics with describe()

`describe()` gives statistics for all numeric columns:
- **count** = how many non-missing values
- **mean** = average
- **std** = how spread out the values are
- **min / max** = smallest and largest value
- **25% / 50% / 75%** = quartiles

⚠️ Look at the min values — some are **negative**, which is impossible for hours!

In [22]:
# df['age '].quantile(0.25)
df['age ']

0       21.048994
1             NaN
2             NaN
3       25.350557
4       17.937754
          ...
1148    20.169749
1149    22.671669
1150    16.382979
1151    20.676107
1152    24.716932
Name: age , Length: 1153, dtype: float64

In [23]:
df.describe()

,age,SOCIAL_MEDIA_HOURS,netflix_hours,attendance_percentage,EXERCISE_FREQUENCY,mental_health_rating,EXAM_SCORE,RANDOM_ID
count,1041.000000,1044.000000,1032.000000,1039.000000,1042.000000,1041.000000,1039.000000,1153.000000
mean,20.429438,2.651652,2.011406,83.906115,2.958623,5.379768,83.807246,5539.029488
std,3.776914,3.244181,3.285012,9.713085,3.603461,4.179635,66.490540,2648.087879
min,9.558960,-8.078218,-9.915100,55.726353,-9.503038,-5.626254,20.223173,1002.000000
25%,17.668028,0.507419,-0.211819,77.715425,0.416286,2.408725,58.843359,3240.000000
50%,20.496321,2.611274,1.937920,83.959410,3.046520,5.390964,71.034216,5530.000000
75%,23.018131,4.788802,4.275851,91.018567,5.355855,8.245798,83.926080,7808.000000
max,31.463841,12.334267,12.414241,106.282568,14.645852,18.141586,502.824692,9993.000000

### Step 19 — Count Missing Values

`isnull()` checks every cell — True if missing, False if not.  
`.sum()` counts the True values per column.  
This tells us exactly how many values are missing in each column.

In [24]:
df.isnull().sum()

student_id                       121
age                              112
GENDER                           114
STUDY_HOURS_PER_DAY              155
SOCIAL_MEDIA_HOURS               109
netflix_hours                    121
PART_TIME_JOB                    121
attendance_percentage            114
SLEEP_HOURS                      109
diet_quality                     106
EXERCISE_FREQUENCY               111
PARENTAL_EDUCATION_LEVEL         206
INTERNET_QUALITY                 110
mental_health_rating             112
EXTRACURRICULAR_PARTICIPATION    114
EXAM_SCORE                       114
RANDOM_ID                          0
dtype: int64

### Step 20 — Count Duplicate Rows

`duplicated()` marks rows that are exact copies of another row.  
`.sum()` counts how many duplicates exist.

In [25]:
df.duplicated().sum()

np.int64(3)

In [26]:
df[df.duplicated()]    #keep=False

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
876,S1873,17.648301,F,4.3,NaN,-3.233988,No,82.252457,-0.489389156,Fair,7.483958,High School,Good,10.956222,No,84.367479,8136
877,S1874,16.940867,M,5.1,2.731454,0.307086,No,95.648970,8.048016356998517,unknown,2.259864,Master,Average,9.087426,No,96.000869,9779
878,S1875,20.513999,femle,7.6,2.040626,NaN,NaN,93.904316,6.40760898746424,Poor,-0.507753,High School,Good,7.078776,NaN,98.565704,7398

### Step 21 — Check Unique Values in a Column

`value_counts()` shows all unique values in a column and how many times each appears.

Look at the GENDER column — we should only have Male, Female, Other. But notice how many messy variations exist!

In [27]:
df['age '].value_counts(dropna=False)

age
NaN          112
17.648301      2
16.940867      2
20.513999      2
21.048994      1
            ...
20.169749      1
22.671669      1
16.382979      1
20.676107      1
24.716932      1
Name: count, Length: 1039, dtype: int64

In [28]:
df['GENDER'].value_counts(dropna=False)

GENDER
NaN         114
MALE        103
 F           99
mle          91
female       89
 M           81
male         79
femle        69
FEMALE       67
 female      53
 male        46
 femle       43
  F          39
 mle         36
 FEMALE      35
 MALE        35
Other        34
  M          30
 Other       10
Name: count, dtype: int64

---
# Part 4 — Cleaning the Data

Real data is almost always messy. Before we analyse it, we must fix it.

Here are the problems we found in our dataset:

| Problem | Example |
|---------|--------|
| Column names have spaces | `'student_id '` instead of `'student_id'` |
| Inconsistent casing | Some columns are UPPERCASE, others lowercase |
| Duplicate rows | Same student appears twice |
| Useless column | `RANDOM_ID` has no meaning |
| Missing values | Many columns have NaN (blank) cells |
| Gender typos | `'femle'`, `'mle'`, `' FEMALE '` all mean different things to pandas |
| Text instead of numbers | `'ten'` written as a word in a numeric column |
| Negative hours | `-3.5` hours of Netflix is impossible |
| Exam scores > 100 | A score of 365 is impossible |

We will fix each one step by step.

---

### Step 22 — Fix Column Names (Remove Spaces)

Some column names have hidden spaces at the start or end. This causes bugs like `df['student_id']` giving a KeyError even though you can see the column.

`str.strip()` removes spaces from both ends.  
`str.lower()` makes everything lowercase — so all column names are consistent.

In [29]:
# Remove spaces and make all column names lowercase
df.columns = df.columns.str.strip().str.lower()

In [30]:
# Verify — all clean now
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score',
       'random_id'],
      dtype='str')

In [31]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714

**Fix Text Numbers in Numeric Columns**

The `study_hours_per_day` and `sleep_hours` columns are supposed to be numbers, but some entries have the word `'ten'` instead of `10`.

`replace()` swaps the text for the correct number string.  
`pd.to_numeric()` then converts the whole column to a proper number type.  
`errors='coerce'` means: if anything still can't be converted, make it NaN instead of crashing.

In [32]:
# # Replace the word 'ten' with the number '10'

df['study_hours_per_day'] = df['study_hours_per_day'].replace('ten', '10')


df['sleep_hours']         = df['sleep_hours'].replace('ten', '10')

In [33]:
# Convert to numeric (number) type

df['study_hours_per_day'] = pd.to_numeric(df['study_hours_per_day'], errors='coerce')
df['sleep_hours']         = pd.to_numeric(df['sleep_hours'],         errors='coerce')

In [34]:
df['sleep_hours'].value_counts()

sleep_hours
10.000000    10
4.900000      3
3.000000      2
3.300000      2
5.500000      2
             ..
2.247229      1
5.185472      1
12.592937     1
5.437463      1
8.437898      1
Name: count, Length: 1023, dtype: int64

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1153 entries, 0 to 1152
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1032 non-null   str
 1   age                            1041 non-null   float64
 2   gender                         1039 non-null   str
 3   study_hours_per_day            998 non-null    float64
 4   social_media_hours             1044 non-null   float64
 5   netflix_hours                  1032 non-null   float64
 6   part_time_job                  1032 non-null   str
 7   attendance_percentage          1039 non-null   float64
 8   sleep_hours                    1044 non-null   float64
 9   diet_quality                   1047 non-null   str
 10  exercise_frequency             1042 non-null   float64
 11  parental_education_level       947 non-null    str
 12  internet_quality               1043 non-null   str
 13  mental_health_rating           1041 non-null   float64
 14  extracurricular_participation  1039 non-null   str
 15  exam_score                     1039 non-null   float64
 16  random_id                      1153 non-null   int64
dtypes: float64(9), int64(1), str(7)
memory usage: 153.3 KB

### Step 23 — Drop a Useless Column

The `random_id` column is just random numbers with no meaning. It has nothing to do with student performance. We remove it with `drop()`.

`columns=['random_id']` tells pandas we are dropping a column (not a row).

In [36]:
# Remove the random_id column

df = df.drop(columns=['random_id'])

In [37]:
# Verify — column is gone, shape should now be 16 columns
df.shape

(1153, 16)

In [38]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

### Step 24 — Remove Duplicate Rows

`drop_duplicates()` removes rows that are exact copies of another row.  
`keep='first'` keeps the first occurrence and removes the rest.  
`reset_index(drop=True)` renumbers the rows cleanly after removal.

In [39]:
# Remove duplicate rows

df = df.drop_duplicates(keep='first')
df = df.reset_index(drop=True)

In [40]:
# Verify — should be 0 now
df.duplicated().sum()

np.int64(0)

### Step 25 — Drop Rows with Missing Student ID

If a student has no ID, we cannot identify them. These rows are useless to us.

`dropna(subset=['student_id'])` drops only the rows where `student_id` is missing (NaN).

In [41]:
df= df.drop(columns=['student_id'])

### Step 26 — Drop Rows with Missing Exam Score

The exam score is the most important column — it's what we want to understand. Rows with no exam score are not useful for our analysis.

In [44]:
# Drop rows where exam_score is missing

df = df.dropna(subset=['exam_score'])
df = df.reset_index(drop=True)

In [45]:
# How many rows do we have now?
df.shape

(1036, 15)

### Step 27 — Fill Missing Numbers with the Median

For numeric columns, we replace missing values with the **median** (the middle value).  
We use median instead of mean because our data has outliers — extreme values can pull the mean far from the typical value, but the median stays representative.

`fillna()` replaces NaN with whatever value you give it.

In [46]:
# Fill missing numeric values with the median of each column
df['age']                  = df['age'].fillna(df['age'].median())
df['social_media_hours']   = df['social_media_hours'].fillna(df['social_media_hours'].median())
df['netflix_hours']        = df['netflix_hours'].fillna(df['netflix_hours'].median())
df['attendance_percentage']= df['attendance_percentage'].fillna(df['attendance_percentage'].median())
df['exercise_frequency']   = df['exercise_frequency'].fillna(df['exercise_frequency'].median())
df['mental_health_rating'] = df['mental_health_rating'].fillna(df['mental_health_rating'].median())

In [47]:
df.isnull().sum().sum()

np.int64(931)

In [48]:
# Check — these columns should now have 0 missing values
df[['age', 'social_media_hours', 'netflix_hours']].isnull().sum()

age                   0
social_media_hours    0
netflix_hours         0
dtype: int64

### Step 28 — Fill Missing Text with the Mode

For text (categorical) columns, we use the **mode** — the most frequently occurring value.  
`mode()[0]` gets the most common value (mode returns a Series, so `[0]` grabs the first/top item).

In [ ]:
df['part_time_job']               = df['part_time_job'].fillna(df['part_time_job'].mode())

In [52]:
df.isnull().sum()

age                                0
gender                           103
study_hours_per_day              145
social_media_hours                 0
netflix_hours                      0
part_time_job                    102
attendance_percentage              0
sleep_hours                      101
diet_quality                      97
exercise_frequency                 0
parental_education_level         181
internet_quality                  98
mental_health_rating               0
extracurricular_participation    104
exam_score                         0
dtype: int64

In [58]:
# Fill missing text columns with the most common value
# [0] is used to get the first (most frequent) value from mode() result.

df['part_time_job']               = df['part_time_job'].fillna(df['part_time_job'].mode()[0])
df['diet_quality']                = df['diet_quality'].fillna(df['diet_quality'].mode()[0])
df['internet_quality']            = df['internet_quality'].fillna(df['internet_quality'].mode()[0])
df['extracurricular_participation']= df['extracurricular_participation'].fillna(df['extracurricular_participation'].mode()[0])

In [ ]:
#We cannot guess personal identity attributes —
# filling with the mode would fabricate demographic data, introducing bias into the AI model.

In [ ]:
# Missing categorical values are filled with "Unknown" to avoid wrong assumptions and keep missing data information...Added Bias.
# Fill gender and parental education with 'Unknown'

df['gender']                   = df['gender'].fillna('Unknown')
df['parental_education_level'] = df['parental_education_level'].fillna('Unknown')

### Step 29 — Fix Spaces in the Gender Column

The gender column is very messy. It has:
- Leading/trailing spaces: `' male '` instead of `'male'`
- Mixed case: `'MALE'`, `'Male'`, `'male'`
- Typos: `'mle'` instead of `'male'`, `'femle'` instead of `'female'`

We first strip spaces and make everything lowercase to reduce the chaos.

In [59]:
# Strip spaces and make lowercase
df['gender'] = df['gender'].str.strip().str.lower()

In [60]:
# See what values remain after stripping and lowercasing
df['gender'].value_counts()

gender
male      234
female    222
f         126
mle       114
m          99
femle      98
other      40
Name: count, dtype: int64

### Step 30 — Map Gender to Clean Standard Values

Now we use a **dictionary** to map every messy variant to the correct clean value.  
`map()` replaces each value using the dictionary — like a lookup table.

In [61]:
# Map all messy variants to clean standard values
gender_map = {
    'female'  : 'Female',
    'femle'   : 'Female',
    'f'       : 'Female',
    'male'    : 'Male',
    'mle'     : 'Male',
    'm'       : 'Male',
    'other'   : 'Other',
    'unknown' : 'Unknown'
}

df['gender'] = df['gender'].map(gender_map).fillna('Unknown')

In [62]:
# Verify — should now have only 4 clean values
df['gender'].value_counts()

gender
Male       447
Female     446
Unknown    103
Other       40
Name: count, dtype: int64

### Step 31 — Fix Spaces in Other Categorical Columns

Other text columns also have leading/trailing spaces causing the same problem — `'No'` and `' No'` look different to pandas but mean the same thing.

`str.strip()` removes the spaces. `str.title()` makes it Title Case (first letter uppercase).

In [63]:
# Strip spaces and standardise casing for all these columns
text_columns = [
    'part_time_job',
    'diet_quality',
    'internet_quality',
    'extracurricular_participation',
    'parental_education_level'
]

for col in text_columns:
    df[col] = df[col].str.strip().str.title()

In [64]:
# Verify — should show clean values like 'Yes', 'No' not ' Yes' and ' No'
df['part_time_job'].value_counts()

part_time_job
No     838
Yes    198
Name: count, dtype: int64

### Step 32 — Fix Text Numbers in Numeric Columns

The `study_hours_per_day` and `sleep_hours` columns are supposed to be numbers, but some entries have the word `'ten'` instead of `10`.

`replace()` swaps the text for the correct number string.  
`pd.to_numeric()` then converts the whole column to a proper number type.  
`errors='coerce'` means: if anything still can't be converted, make it NaN instead of crashing.

In [65]:
# Fill any remaining NaN created during conversion
df['study_hours_per_day'] = df['study_hours_per_day'].fillna(df['study_hours_per_day'].median())
df['sleep_hours']         = df['sleep_hours'].fillna(df['sleep_hours'].median())

In [66]:
# Verify data type is now float64, not object
df[['study_hours_per_day', 'sleep_hours']].dtypes

study_hours_per_day    float64
sleep_hours            float64
dtype: object

### Step 33 — Remove Negative Hours (Impossible Values)

You cannot spend a negative number of hours watching Netflix or on social media. These are data entry errors.

`clip(lower=0)` replaces any value below 0 with 0. It **clips** the values to a valid range.

In [67]:
# Set the minimum value to 0 — hours cannot be negative
df['netflix_hours']      = df['netflix_hours'].clip(lower=0)
df['social_media_hours'] = df['social_media_hours'].clip(lower=0)
df['exercise_frequency'] = df['exercise_frequency'].clip(lower=0)
df['sleep_hours']        = df['sleep_hours'].clip(lower=0, upper=16)

In [68]:
# Verify — no more negative values in netflix_hours
df['netflix_hours'].min()

np.float64(0.0)

### Step 34 — Fix Exam Scores Above 100

An exam score cannot be above 100%. Some values are clearly wrong (e.g., 365, 502). We cap all scores at 100 using `clip()`.

In [69]:
# Before — how many scores are above 100?
(df['exam_score'] > 100).sum()

np.int64(84)

In [70]:
# Cap exam score between 0 and 100
df['exam_score'] = df['exam_score'].clip(lower=0, upper=100)

In [71]:
# Verify — max should now be 100
df['exam_score'].max()

np.float64(100.0)

### Step 35 — Remove Rows with Unrealistic Age

Some students have an age of less than 15 — unrealistic for university students. We remove these rows entirely using boolean filtering.

In [72]:
# Keep only rows where age is 15 or older
df = df[df['age'] >= 15]
df = df.reset_index(drop=True)

In [73]:
# Verify — minimum age should now be 15 or above
df['age'].min()

np.float64(15.018135762187722)

### Step 36 — Check the Clean Dataset

Let's do a final check to see how much our data improved.

In [74]:
# Final shape of the clean data
df.shape

(967, 15)

In [75]:
# Final missing value check — should be mostly 0
df.isnull().sum()

age                                0
gender                             0
study_hours_per_day                0
social_media_hours                 0
netflix_hours                      0
part_time_job                      0
attendance_percentage              0
sleep_hours                        0
diet_quality                       0
exercise_frequency                 0
parental_education_level         172
internet_quality                   0
mental_health_rating               0
extracurricular_participation      0
exam_score                         0
dtype: int64

In [76]:
# Look at the clean data
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,21.048994,Female,0.0,0.029056,4.799806,No,86.153500,7.294123,Fair,6.517918,Master,Good,11.789345,Yes,59.197075
1,20.508308,Female,4.1,3.539930,3.400655,No,83.979009,1.711612,Good,4.408856,High School,Average,5.432582,No,98.718319
2,20.508308,Male,4.1,10.270434,1.780307,No,92.813065,0.245307,Poor,0.000000,NaN,Poor,-3.244017,No,33.361684
3,25.350557,Female,10.0,0.816828,5.861446,No,70.689033,4.632657,Poor,0.581851,Master,Good,5.000688,Yes,27.830878
4,17.937754,Female,10.0,5.320886,0.000000,No,83.979009,5.466443,Fair,5.148622,Master,Good,2.408725,No,60.686418

In [ ]:
# Save the clean data
df.to_csv('student_data_clean.csv', index=False)

---
# Part 5 — Selecting and Filtering Data

Now that our data is clean, let's learn how to **find specific rows and columns** we care about.

---

### Step 37 — Select by Label with loc

`loc[row, column]` selects data using **labels** (names).  
- Row label = the index number (0, 1, 2, ...)
- Column label = the column name

The format is: `df.loc[rows, columns]`

In [ ]:
# Get rows 0 to 4, only these specific columns
df.loc[0:4, ['student_id', 'age', 'gender', 'exam_score']]

### Step 38 — Select by Position with iloc

`iloc[row, column]` selects data using **position numbers** (like Python list indexing).  
0 = first, 1 = second, -1 = last

In [ ]:
# Get first 3 rows, first 4 columns (by position)
df.iloc[0:3, 0:4]

### Step 39 — Filter Rows with a Condition

This is called **boolean masking**. We write a condition, and pandas returns only the rows where that condition is True.

Think of it like asking a question: "Which rows have exam_score above 85?"

In [ ]:
# Show only students who scored above 85
df[df['exam_score'] > 85]

### Step 40 — Filter with Two Conditions

Use `&` for AND (both must be true), `|` for OR (either must be true).  
⚠️ Always put each condition in its own parentheses `()`!

In [ ]:
# Students who scored above 80 AND study more than 5 hours
df[(df['exam_score'] > 80) & (df['study_hours_per_day'] > 5)]

### Step 41 — Filter with isin()

`isin()` filters rows where a value is in a given list. Like saying "give me rows where internet_quality is either Good or Average".

In [ ]:
# Students with Good or Average internet quality
df[df['internet_quality'].isin(['Good', 'Average'])]

---
# Part 6 — Creating New Columns
---

### Step 42 — Create a Column with Simple Math

We can create a new column by doing arithmetic on existing columns. Pandas applies the operation to every row automatically.

In [ ]:
# Total screen time = social media + netflix
df['total_screen_time'] = df['social_media_hours'] + df['netflix_hours']

In [ ]:
# Check the new column
df[['social_media_hours', 'netflix_hours', 'total_screen_time']].head()

### Step 43 — Create a Column Using a Function

`apply()` runs a function on every row. We define a function that converts a score into a letter grade, then apply it to the entire column.

In [ ]:
# Define a function that converts score to grade
def get_grade(score):
    if score >= 85:   return 'A'
    elif score >= 70: return 'B'
    elif score >= 55: return 'C'
    elif score >= 40: return 'D'
    else:             return 'F'

# Apply it to every row in the exam_score column
df['grade'] = df['exam_score'].apply(get_grade)

In [ ]:
# See the grade distribution
df['grade'].value_counts()

### Step 44 — Create a Column Using pd.cut()

`pd.cut()` groups a continuous number into categories (bins).  
Here we split students into age groups.

In [ ]:
# Create age groups
df['age_group'] = pd.cut(
    df['age'],
    bins   = [14, 18, 21, 24, 35],
    labels = ['15-18', '19-21', '22-24', '25+']
)

In [ ]:
# See age group distribution
df['age_group'].value_counts().sort_index()

---
# Part 7 — Sorting and Ranking
---

### Step 45 — Sort the Data

`sort_values()` sorts the DataFrame by one or more columns.  
`ascending=False` means largest first (descending order).

In [ ]:
# Sort by exam score — highest first
df.sort_values('exam_score', ascending=False).head(10)

### Step 46 — Get the Top N Rows

`nlargest()` is a shortcut to get the top N rows for a given column.

In [ ]:
# Top 5 students by exam score
df.nlargest(5, 'exam_score')[['student_id', 'exam_score', 'study_hours_per_day']]

---
# Part 8 — Grouping and Aggregating

GroupBy is one of the most powerful tools in Pandas. It answers questions like:
- "What is the average score for each gender?"
- "How many students are in each grade?"

It works in 3 steps: **Split** → **Apply** → **Combine**

---

### Step 47 — Average Score by Gender

`groupby('gender')` splits the data into groups — one for each gender.  
Then we pick a column and apply `.mean()` to get the average within each group.

In [ ]:
# Average exam score for each gender
df.groupby('gender')['exam_score'].mean().round(2)

### Step 48 — Count Students in Each Grade

`count()` counts how many students fall in each group.

In [ ]:
# How many students got each grade?
df.groupby('grade')['student_id'].count()

### Step 49 — Multiple Statistics at Once with agg()

`agg()` lets you calculate several statistics for each group at the same time.  
This is great for building a summary table.

In [ ]:
# Summary table: count, avg score, avg study hours — grouped by grade
df.groupby('grade').agg(
    Students        = ('student_id', 'count'),
    Avg_Score       = ('exam_score', 'mean'),
    Avg_Study_Hours = ('study_hours_per_day', 'mean'),
    Avg_Sleep       = ('sleep_hours', 'mean')
).round(2)

### Step 50 — Pivot Table

A pivot table is like a cross-tabulation — rows are one category, columns are another, and cells are the value you want to see.

In [ ]:
# Average exam score by diet quality (rows) and internet quality (columns)
pd.pivot_table(
    df,
    values  = 'exam_score',
    index   = 'diet_quality',
    columns = 'internet_quality',
    aggfunc = 'mean'
).round(1)

---
# Part 9 — Quick Analysis
---

### Step 51 — Correlation Between Columns

`corr()` measures how strongly two columns are related.
- Values close to **1.0** = strong positive relationship (one goes up, other goes up)
- Values close to **-1.0** = strong negative relationship (one goes up, other goes down)
- Values close to **0** = no clear relationship

In [ ]:
# Correlation of key columns with exam_score
cols = ['exam_score', 'study_hours_per_day', 'sleep_hours',
        'total_screen_time', 'attendance_percentage', 'mental_health_rating']

df[cols].corr()[['exam_score']].round(3)

### Step 52 — Cross Tabulation

`pd.crosstab()` counts how many students fall into each combination of two categories. Great for seeing patterns.

In [ ]:
# How many students of each gender got each grade?
pd.crosstab(df['gender'], df['grade'])

---
# Part 10 — Saving the Clean Data
---

### Step 53 — Save to CSV

`to_csv()` saves the DataFrame as a CSV file.  
`index=False` means we don't save the row numbers (0, 1, 2...) — they are not real data.

In [ ]:
# Reload and verify it saved correctly
pd.read_csv('student_data_clean.csv').shape

---
# 🏋️ Practice Exercises

Try these on your own using the clean `df` dataset.

---

**Exercise 1**  
Show all students who have a part-time job **and** got a grade of 'A'.

**Exercise 2**  
What is the average `study_hours_per_day` for each `grade`?

**Exercise 3**  
How many students have `Good` internet quality?

**Exercise 4**  
Create a new column called `sleep_enough` that is `True` if `sleep_hours >= 7`, else `False`.

**Exercise 5**  
Find the student with the highest `total_screen_time`. What was their exam score?

**Exercise 6**  
What percentage of students got each grade? (Hint: use `value_counts(normalize=True)`)

**Exercise 7**  
Sort students by `study_hours_per_day` (highest first) and show the top 5 rows.

**Exercise 8**  
Group by `part_time_job` and find the average `exam_score` for each group.  
Do students without a job score higher?

---

In [ ]:
# Exercise 1 — Your answer here

In [ ]:
# Exercise 2 — Your answer here

In [ ]:
# Exercise 3 — Your answer here

In [ ]:
# Exercise 4 — Your answer here

In [ ]:
# Exercise 5 — Your answer here

In [ ]:
# Exercise 6 — Your answer here

In [ ]:
# Exercise 7 — Your answer here

In [ ]:
# Exercise 8 — Your answer here

---
# ✅ What You Learned

| Topic | What you can do |
|-------|-----------------|
| Series & DataFrame | Create, access, and understand both structures |
| Loading data | `pd.read_csv()` to load any CSV file |
| Exploring | `head()`, `info()`, `describe()`, `isnull()` |
| Cleaning | Fix column names, drop duplicates, fill NaN, fix typos, handle outliers |
| Selecting | `loc`, `iloc`, boolean filtering, `isin()` |
| New columns | Arithmetic, `apply()`, `pd.cut()` |
| Sorting | `sort_values()`, `nlargest()` |
| GroupBy | `groupby()`, `agg()`, `pivot_table()` |
| Analysis | `corr()`, `crosstab()`, `value_counts()` |
| Saving | `to_csv()` |

---

**Next Step → Matplotlib & Seaborn:** Visualise these insights with charts and graphs.

---
*Pandas Beginner Notebook — AI Foundations Course*